"""Create products table

Revision ID: ac43fee11815
Revises: be021b8db479
Create Date: 2026-05-02 09:10:55.774223
"""
from alembic import op
import sqlalchemy as sa


revision = 'ac43fee11815'
down_revision = 'be021b8db479'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
