"""Create products table

Revision ID: be021b8db479
Revises: 002
Create Date: 2026-05-02 09:10:00.092439
"""
from alembic import op
import sqlalchemy as sa


revision = 'be021b8db479'
down_revision = '002'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_title'), 'product', ['title'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_title'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    # ### end Alembic commands ###
